### ISSUE TITLE
请问运行之后出现这种报错是什么原因，怎么解决

### ISSUE THREAD

**Issue by nan2002321** [TransparentLC/realesrgan-gui#11]
Using executable: D:\APP\Realesrgan_GUI\realesrgan-ncnn-vulkan.exe
vkCreateInstance failed -9
vkCreateInstance failed -9
invalid gpu device
Traceback (most recent call last):
  File "task.py", line 243, in taskRunner
  File "task.py", line 95, in run
subprocess.CalledProcessError: Command '('D:\\APP\\Realesrgan_GUI\\realesrgan-ncnn-vulkan.exe', '-v', '-i', 'C:\\Users\\86177\\Pictures\\Saved Pictures\\1.png', '-o', 'C:\\Users\\86177\\AppData\\Local\\Temp\\JBhfeTEjokb1UD6h.png', '-s', '4', '-t', '256', '-n', 'realesrgan-x4plus-anime', '-g', '0', '')' returned non-zero exit status 4294967295.

**Comment by TransparentLC** [comment]
正常情况下可以运行时会先显示出可用的显卡型号的，先试一下更新显卡驱动？

另外你的显卡是否支持 Vulkan？很多比较旧的型号并不支持，应该也就无法使用。

**Comment by nan2002321** [comment]
感谢您愿意解答我的疑问，我的笔记本显卡是1650，驱动也已经是最新，不知道为什么程序能在另一台1650笔记本的运行，而我的不能




1911849284
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TransparentLC/realesrgan-gui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 晚上9:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TransparentLC/realesrgan-gui] 请问运行之后出现这种报错是什么原因，怎么解决 (Issue #11)





 
正常情况下可以运行时会先显示出可用的显卡型号的，先试一下更新显卡驱动？
 
另外你的显卡是否支持 Vulkan？很多比较旧的型号并不支持，应该也就无法使用。

**Comment by TransparentLC** [comment]
1650 的话按理来说应该是支持的，不过就算是 Real-ESRGAN ncnn Vulkan 用的 [ncnn-vulkan 框架那边的 FAQ](https://github.com/Tencent/ncnn/wiki/faq#vkcreateinstance-failed--9) 也只是建议更新驱动😂

或许可以重装一下试试看？不过还不行的话，这毕竟不是 GUI 部分的问题，也可以试试去 Real-ESRGAN ncnn Vulkan 的 issue 区反馈。

**Comment by nan2002321** [comment]
好的，感谢您的解答




1911849284
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TransparentLC/realesrgan-gui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 晚上10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TransparentLC/realesrgan-gui] 请问运行之后出现这种报错是什么原因，怎么解决 (Issue #11)





 
1650 的话按理来说应该是支持的，不过就算是 Real-ESRGAN ncnn Vulkan 用的 ncnn-vulkan 框架那边的 FAQ 也只是建议更新驱动😂
 
或许可以重装一下试试看？不过还不行的话，这毕竟不是 GUI 部分的问题，也可以试试去 Real-ESRGAN ncnn Vulkan 的 issue 区反馈。

**Comment by VwEl** [comment]
> 正常情况下可以运行时会先显示出可用的显卡型号的，先试一下更新显卡驱动？
> 
> 另外你的显卡是否支持 Vulkan？很多比较旧的型号并不支持，应该也就无法使用。

我用vega56也会报这个提示。不过上面是两张卡的信息，然后就是报错内容Traceback (most recent call last):   File "task.py", line 243, in taskRunner  File "task.py", line 95, in run 到后面那部分。选副卡Arc380就能正常运行，挺迷惑的

这是我两张卡的信息
[0 Radeon RX Vega]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX Vega]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX Vega]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Radeon RX Vega]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) Arc(TM) A380  Graphics]  queueC=1[1]  queueG=0[1]  queueT=2[1]
[1 Intel(R) Arc(TM) A380  Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) Arc(TM) A380  Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) Arc(TM) A380  Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

**Comment by VwEl** [comment]
> 正常情况下可以运行时会先显示出可用的显卡型号的，先试一下更新显卡驱动？
> 
> 另外你的显卡是否支持 Vulkan？很多比较旧的型号并不支持，应该也就无法使用。

开启TTA模式也能正常运行，关了就报错

**Comment by qkhhssyvw** [comment]
Using executable: C:\Users\lin\Desktop\realesrgan-gui-windows-bundled-v0.2.5.0\realesrgan-ncnn-vulkan.exe
[0 NVIDIA GeForce GTX 1050 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1050 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1050 Ti]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1050 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
0.00%
vkWaitForFences failed -4
2.00%
vkQueueSubmit failed -4
4.00%
6.00%
8.00%
10.00%
12.00%
vkWaitForFences failed -4
14.00%
16.00%
18.00%
20.00%
22.00%
24.00%
26.00%
28.00%
30.00%
32.00%
34.00%
36.00%
38.00%
40.00%
42.00%
44.00%
46.00%
48.00%
50.00%
52.00%
54.00%
56.00%
58.00%
60.00%
62.00%
64.00%
66.00%
68.00%
70.00%
72.00%
74.00%
76.00%
78.00%
80.00%
82.00%
84.00%
86.00%
88.00%
90.00%
92.00%
94.00%
96.00%
98.00%
C:\Users\lin\Desktop\6d5d374382568266d35066fb52f60dcc.jpg -> C:\Users\lin\AppData\Local\Temp\Zz3wkP6GfMtEojd2.png done
这个是上面问题
