### ISSUE TITLE
建议增加realsr模型

### ISSUE THREAD

**Issue by blacklein** [TransparentLC/realesrgan-gui#12]
经过实测，realsr模型在现实照片上的放大效果胜过real-esrgan模型，希望作者能增加realsr模型放大选项，谢谢~
https://github.com/nihui/realsr-ncnn-vulkan

**Comment by blacklein** [comment]
换了几张照片效果有较大波动

**Comment by TransparentLC** [comment]
之前也注意到了 Real-SR 或者 Real-CUGAN 这些其他的图片放大工具，具体的放大效果我没有对比过，但是真的要做 GUI 的话我目前的想法会更倾向于复用这里的代码然后再开一个 repo 来着……

不过最近空余时间比较少，即使我有对这两个做 GUI 的打算也需要再等比较长的一段时间才会有精力动手（

**Comment by blacklein** [comment]
原图
![447380d09d4f1dfb3448eef624b23f76](https://user-images.githubusercontent.com/69177971/202859061-7f95fe25-ec44-4542-ac30-c0d05fe95ef3.jpeg)

real-esrgan放大过度锐化已经严重失真了
![447380d09d4f1dfb3448eef624b23f76-esrgan](https://user-images.githubusercontent.com/69177971/202859090-d3a026b7-e2cb-40dc-b60f-347d57da2c2b.jpg)

realsr放大各方面细节要好很多，这是在原图本身细节损失很严重的情况下，如果原图稍微好点，realsr的效果会很好
![447380d09d4f1dfb3448eef624b23f76-realsr](https://user-images.githubusercontent.com/69177971/202859143-0d5b7a77-a2d8-4ed3-952d-e4b3cb2eb091.jpg)

**Comment by blacklein** [comment]
开两个repo是说每个模型一个独立的gui？那可能有点不方便，可能的话还是想能做成一个gui，二次元用real-esrgan，三次元用realsr，其他模型我自己测试下来也没有特别大的优势，这两个模型基本能涵盖绝大多数使用场景了
