### ISSUE TITLE
一个命名的小bug

### ISSUE THREAD

**Issue by zdrzdr** [TransparentLC/realesrgan-gui#16]
修改模型后处理命名不会改变，只有重新拖入文件处理才会刷新命名

**Comment by TransparentLC** [comment]
这个已经加上了～

目前的做法是，如果没有自己改变过输出文件的路径（在文本框里输入，或通过“浏览”在对话框中选择），则修改模型和放大尺寸就会自动刷新命名。

改变过路径的话自动刷新就禁用了，下次通过拖入或“浏览”对话框设置输入文件时会重新启用。
