### ISSUE TITLE
main.py代码中的一个问题

### ISSUE THREAD

**Issue by stillstream** [TransparentLC/realesrgan-gui#19]
360行
match self.varintResizeMode.get():
能请教下这种是什么用法么，之前没有见过，在pycharm也是报语法错误

**Comment by TransparentLC** [comment]
https://docs.python.org/zh-cn/3/tutorial/controlflow.html#match-statements

Python 3.10 加入的 `match`，这个语句的作用类似于其他编程语言的 `switch`。

**Comment by stillstream** [comment]
感谢赐教。
我在ubuntu20.04上运行的时候报错Error loading Python lib '/tmp/_MEIWA7DVD/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/_MEIWA7DVD/libpython3.11.so.1.0)
这个不会也是由于python版本导致的把

**Comment by TransparentLC** [comment]
这个是 glibc 的版本不够，20.04 的话对应的应该是 glibc 2.31。
因为现在用 actions 打包是在 22.04 上进行的所以要求的 glibc 最低版本也提高了，我忘记改 readme 了😂
