### ISSUE TITLE
Request : add imgs output quality option

### ISSUE THREAD

**Issue by FlotingDream** [TransparentLC/realesrgan-gui#2]
Request : add imgs output quality option

like :

cv2.imwrite(*,* ,[int(cv2.IMWRITE_WEBP_QUALITY),75])

**Comment by TransparentLC** [comment]
In other words, do you need lossy outputs?

**Comment by FlotingDream** [comment]
Yep for manga batch SR, webp 75 is a good choice.

**Comment by TransparentLC** [comment]
Added "Enable lossy compression" and "Lossy compression quality" in advanced config. You can download the latest application from Actions to try it out.

**Comment by FlotingDream** [comment]
works fine, thx! 
Any chance to save settings?

**Comment by TransparentLC** [comment]
The result is as expected:

* If the output is a JPEG/WebP file, the input file will be upscaled to a temporary lossless WebP file (Real-ESRGAN-ncnn-vulkan only supports lossless WebP output). Then the GUI applies lossy compression on the temporary file and saves as the output file.
* If the input is a directory, the output files' extensions are the same as the corresponding input files.
* Currently, if you want to upscale a directory with JPEGs and get WebPs, I suggest that you can change the input files' extensions to WebP before upscaling. You can use PowerShell command `Get-ChildItem *.jpg | Rename-Item -NewName { [IO.Path]::ChangeExtension($_.Name, "webp") }` or other tools like PowerRename in PowerToys to rename the files at once.

Now the settings will be saved to `config.ini` in the same directory as the application.

**Comment by FlotingDream** [comment]
It is clear, thx!
:)

**Comment by TransparentLC** [comment]
I will create a new release with these changes.

**Comment by FlotingDream** [comment]
Some Error occur?  some temp error?
-------------------------------------------
image C:\Users\xxxxxx\AppData\Local\Temp\txo6gBGwfmPIN_NX.png has alpha channel ! C:\Users\xxxxxx\AppData\Local\Temp\txo6gBGwfmPIN_NX.png will output C:\Users\xxxxxx\AppData\Local\Temp\0XIbaWAMsq_aH5ps.jpg.png
0.00%
vkQueueSubmit failed -4
5.00%
vkQueueSubmit failed -4
10.00%
vkQueueSubmit failed -4
15.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
20.00%
vkQueueSubmit failed -4
25.00%
vkQueueSubmit failed -4
30.00%
vkQueueSubmit failed -4
35.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
40.00%
vkQueueSubmit failed -4
45.00%
vkQueueSubmit failed -4
50.00%
vkQueueSubmit failed -4
55.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
60.00%
vkQueueSubmit failed -4
65.00%
vkQueueSubmit failed -4
70.00%
vkQueueSubmit failed -4
75.00%
vkQueueSubmit failed -4
vkQueueSubmit failed -4
vkQueueSubmit failed -4
80.00%
vkQueueSubmit failed -4
85.00%
vkQueueSubmit failed -4
90.00%
vkQueueSubmit failed -4
95.00%
vkQueueSubmit failed -4
C:\Users\xxxxxx\AppData\Local\Temp\txo6gBGwfmPIN_NX.png -> C:\Users\xxxxxx\AppData\Local\Temp\0XIbaWAMsq_aH5ps.jpg.png done
Traceback (most recent call last):
  File "shutil.py", line 815, in move
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\0XIbaWAMsq_aH5ps.jpg' -> 'D:\\Upscale\\018-028-x4\\0101.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "task.py", line 243, in taskRunner
  File "task.py", line 103, in run
  File "shutil.py", line 835, in move
  File "shutil.py", line 434, in copy2
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxxx\\AppData\\Local\\Temp\\0XIbaWAMsq_aH5ps.jpg'

**Comment by TransparentLC** [comment]
The "vkQueueSubmit failed" error belongs to real-esrgan-ncnn-vulkan (VRAM exceeded?) but not this GUI. You can try to use a smaller tile size (Advanced config).

**Comment by FlotingDream** [comment]
> The "vkQueueSubmit failed" error belongs to real-esrgan-ncnn-vulkan (VRAM exceeded?) but not this GUI. You can try to use a smaller tile size (Advanced config).

worked!
---------------------
By the way, small suggestion:
"If the input is a directory, the output files' extensions are the same as the corresponding input files."
you can try to replace the ext before use real-esrgan-ncnn-vulkan if choose the webp option. :)
