### ISSUE TITLE
处理失败是显卡不支持还是环境问题？

### ISSUE THREAD

**Issue by oldmenplus** [TransparentLC/realesrgan-gui#25]
![QQ截图20230311052712](https://user-images.githubusercontent.com/24629065/224431916-e160bd6e-8a3f-41ba-911e-c25ab47883c4.jpg)

换成RX580显卡就一直处理失败了，难道是显卡不支持？

**Comment by TransparentLC** [comment]
可能是环境问题，把这里显示的命令 `realesrgan-ncnn-vulkan -v -i ... -o ... -s 4 -t 0 -n ... -g auto` 在命令行里执行一下试试看？

3221225781 这个 exit code 一般指的是缺了 DLL，对于 `realesrgan-ncnn-vulkan` 来说最有可能缺的是 `vulkan-1.dll`，可以试试更新显卡驱动或者自己把这个 dll 装上。

**Comment by oldmenplus** [comment]
> 可能是环境问题，把这里显示的命令 `realesrgan-ncnn-vulkan -v -i ... -o ... -s 4 -t 0 -n ... -g auto` 在命令行里执行一下试试看？
> 
> 3221225781 这个 exit code 一般指的是缺了 DLL，对于 `realesrgan-ncnn-vulkan` 来说最有可能缺的是 `vulkan-1.dll`，可以试试更新显卡驱动或者自己把这个 DLL 装上（在我这里的路径是 `C:\WINDOWS\SYSTEM32\vulkan-1.dll`）。

对诶，模拟器也用不了vulkan。

我试试

**Comment by oldmenplus** [comment]
> 可能是环境问题，把这里显示的命令 `realesrgan-ncnn-vulkan -v -i ... -o ... -s 4 -t 0 -n ... -g auto` 在命令行里执行一下试试看？
> 
> 3221225781 这个 exit code 一般指的是缺了 DLL，对于 `realesrgan-ncnn-vulkan` 来说最有可能缺的是 `vulkan-1.dll`，可以试试更新显卡驱动或者自己把这个 DLL 装上（在我这里的路径是 `C:\WINDOWS\SYSTEM32\vulkan-1.dll`）。

耶，搞定，是580的破驱动有问题，害我模拟器也用不了，更新了就好了
![QQ图片20230305125358](https://user-images.githubusercontent.com/24629065/224475272-7adcab6b-4097-47de-bd41-01f7b8fd1d8f.jpg)

**Comment by woshichenghaibo** [comment]
> > 可能是环境问题，把这里显示的命令 `realesrgan-ncnn-vulkan -v -i ... -o ... -s 4 -t 0 -n ... -g auto` 在命令行里执行一下试试看？
> > 3221225781 这个 exit code 一般指的是缺了 DLL，对于 `realesrgan-ncnn-vulkan` 来说最有可能缺的是 `vulkan-1.dll`，可以试试更新显卡驱动或者自己把这个 DLL 装上（在我这里的路径是 `C:\WINDOWS\SYSTEM32\vulkan-1.dll`）。
> 
> 耶，搞定，是580的破驱动有问题，害我模拟器也用不了，更新了就好了 ![QQ图片20230305125358](https://user-images.githubusercontent.com/24629065/224475272-7adcab6b-4097-47de-bd41-01f7b8fd1d8f.jpg)

怎么搞定的？
