### ISSUE TITLE
希望加入多线程支持

### ISSUE THREAD

**Issue by zhengqwe** [TransparentLC/realesrgan-gui#26]
可通过`realesrgan-ncnn-vulkan`的`-j`参数设置

**Comment by TransparentLC** [comment]
主要的速度瓶颈应该是 GPU 性能，这个线程数的影响不大。

刚刚我自己测试了一下，把 1920x1080 的图片放大 4x，测试五次，使用默认的 `-j 1:2:2` 的平均时间是 79s，把线程数翻倍设成 `-j 2:4:4` 的话是 89s，反而更慢了？
