### ISSUE TITLE
windows 11.安全警告。如图

### ISSUE THREAD

**Issue by yiiyahui** [TransparentLC/realesrgan-gui#28]
![螢幕擷取畫面 2023-03-22 220220](https://user-images.githubusercontent.com/30188835/226928988-f17e1161-e841-4935-b665-a5339c3d463b.png)

**Comment by TransparentLC** [comment]
显然是误报，添加白名单吧

**Comment by Reilkay** [comment]
同样的问题（

**Comment by TransparentLC** [comment]
等我试一下按照 https://learn.microsoft.com/zh-cn/microsoft-365/security/intelligence/submission-guide 这里说的提交一下反馈...

各位有微软账号的也可以试试看 (=ﾟωﾟ)=

**Comment by Reilkay** [comment]
> 等我试一下按照 https://learn.microsoft.com/zh-cn/microsoft-365/security/intelligence/submission-guide 这里说的提交一下反馈...
> 
> 各位有微软账号的也可以试试看 (=ﾟωﾟ)=

暂且提交了一下，看看是否有回复吧

**Comment by TransparentLC** [comment]
我这里已经提交完了，回复如下：

> realesrgan-gui.zip
> 
> Submission ID: ...
> Status: Completed
> Submitted by: ...
> Submitted: Apr 5, 2023 12:03:09
> User Opinion: Incorrect detection
> 
> Analyst comments:
> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.
