### ISSUE TITLE
IndentationError: expected an indented block after 'if' statement on line 42

### ISSUE THREAD

**Issue by chenmz430** [TransparentLC/realesrgan-gui#29]
请问执行main.py程序时出现这个报错是什么情况？
May I ask what happens when this error occurs during the execution of main.py program?

**Comment by TransparentLC** [comment]
是哪个文件的 42 行？
我看了一下 main.py 和 task.py 的 42 行都不是 `if` 语句。

**Comment by chenmz430** [comment]
你好，我运行main.py文件，报的这个错



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月04日 11:59 |
| 收件人 | ***@***.***> |
| 抄送至 | Mingze ***@***.***>***@***.***> |
| 主题 | Re: [TransparentLC/realesrgan-gui] IndentationError: expected an indented block after 'if' statement on line 42 (Issue #29) |

是哪个文件的 42 行？
我看了一下 main.py 和 task.py 的 42 行都不是 if 语句。

**Comment by TransparentLC** [comment]
不知道怎么回事。
我开发的时候用的是 Python 3.10 和 3.11，要是真的有 IndentationError 那应该完全运行不了才对……
