### ISSUE TITLE
添加模型图片的评价指标

### ISSUE THREAD

**Issue by chenmz430** [TransparentLC/realesrgan-gui#30]
请问作者能添加一个模型图片的评价指标这个功能么，或者请问怎么添加

**Comment by TransparentLC** [comment]
这个工具只是用来方便放大图片用的，用来衡量模型性能的话已经超出设计的使用范围了（

你可以使用 [ImageMagick](https://imagemagick.org/) 等工具来计算两张**相同大小**的图片的 PSNR、SSIM 等指标：

```shell
magick compare -metric SSIM a.png b.png difference.png
```

比较不同模型的放大效果应该需要大量的图片用来进行测试，在这种情况下自己写脚本来批量放大图片和计算、记录这些指标（可能还需要考虑主观评价？）应该更容易满足你的需求。
