### ISSUE TITLE
Windows 7 is not supported

### ISSUE THREAD

**Issue by Baker7** [TransparentLC/realesrgan-gui#35]
Windows 7 is not supported, but I was offered a download for Windows 7.

It worked great on my Mac , though!  Thanks.

**Comment by TransparentLC** [comment]
Microsoft has ended support for Windows 7 in 2020.

If you really need to run the GUI on Windows 7, make sure `realesrgan-ncnn-vulkan.exe` works on Windows 7 first, then I can give you a build using Python 3.8 (the last Python version which supports Windows 7) separately.

**Comment by Baker7** [comment]
Rephrase ... I understand that Windows 7 is not supported.  You can't control Python etc, that is beyond your control.

Using Windows 7, I was offered a Windows 7 download of this great tool (which didn't work).

What should have happened was instead "Your operating system version is not supported" or something to that effect.

Anyway, excellent work!  I love this tool.

**Comment by TransparentLC** [comment]
Thank you for your support!

Unfortunately I couldn't add the "not supported" hint, Python 3.9+ can't run at all on Windows 7 because of the missing "api-ms-win-core-***.dll" error.
