### ISSUE TITLE
请问转换后的图片文件，可否考虑增加 jxl 格式的输出呢？

### ISSUE THREAD

**Issue by Benson1997** [TransparentLC/realesrgan-gui#37]
从**jpg → jxl**，图片体积可以大幅压缩，而且此过程完全是无损和可逆的。

我把一张【9.42m】的jpg，用XNview无损导出 jxl格式，文件体积压缩到了【1.15m】。经过测试，再将 这个jxl转回 jpg，体积还是【9.42m】，清晰度完全一样。

![图片](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/assets/111626633/2ba06fd1-f8bf-4c58-8ed2-fab399a947b6)

**Comment by Benson1997** [comment]
以下是两个 jxl 介绍的链接：

图片新格式JPEG XL讨论 - 讨论分享 - 小众软件官方论坛
https://meta.appinn.net/t/topic/26546


JPEG XL --- JPEGXL
https://jpegxl.info/

**Comment by TransparentLC** [comment]
PIL 本身还没支持 jxl，目前暂时只能使用第三方包 [jxlpy](https://pypi.org/project/jxlpy/) 添加支持，不过看了一眼这个包居然还没有 cp311 的 wheel……

另外，因为这个工具的主要用途是放大图片而不是转换格式，以及出于程序体积的考虑，我也不太倾向于考虑在工具里附带其他的编码器。我自己的习惯是用工具导出 PNG 再用其他软件转格式。

不过如果有很多人想要一步到位的话，倒是可以考虑加个自定义命令的设定？在放大图片后自动运行这个命令（比如 jxl 的话就是 `cjxl {input} {output} -q 90 -e 9` 这样，要转成 avif 就用 avifenc 的命令等等）来转换格式。

**Comment by Benson1997** [comment]
好的，谢谢，如果量大，还是后期再用其他工具单独也可以。

如果是想要 放大图片后，自动运行 `cjxl {input} {output} -q 90 -e 9`  这个代码的话，这个代码应该加在哪里呢？

**Comment by TransparentLC** [comment]
自定义命令的功能还没做，最近有空的话就会加上。

**Comment by Benson1997** [comment]
好的，谢谢老大。

反馈一下处理中会报错，程序停止的一个情况：

 部分 gif图片，会报错，暂时不知道什么原因。
(Traceback (most recent call last):
  File "task.py", line 244, in taskRunner
  File "task.py", line 190, in run
KeyError: 'duration'
)

您有时间的时候，麻烦帮忙看下哈。

如果出错后，能记录再日志文件里面，并继续处理下一个文件就好了（最后再集中看失败的几个文件）。有时间图片太多，中断后，还要找出来是处理到哪个文件了，然后文件重新放到一个文件夹（或者把已处理过的先暂时删除），比较费时间。

![00001](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/cae3a68b-ba85-4a40-aa0c-a29197ae9433)

**Comment by Benson1997** [comment]
对的，日漫的一些电子书，很多这种gif格式的图片（可能是压缩图片考虑用的gif格式），就一帧，不是动图，哈哈。

**Comment by TransparentLC** [comment]
> 如果出错后，能记录再日志文件里面，并继续处理下一个文件就好了（最后再集中看失败的几个文件）。有时间图片太多，中断后，还要找出来是处理到哪个文件了，然后文件重新放到一个文件夹（或者把已处理过的先暂时删除），比较费时间。

现在加了个“在批处理过程中忽略错误并继续处理”的选项。

不启用的话（和之前一样），在出现错误时：

* 弹出“处理失败”的提醒
* 立即结束处理

启用的话：

* 在出现错误时仍然弹出“处理失败”的提醒
* 继续处理后续的任务（放大图片、分拆/合并 GIF、压缩图片等），对于同一个文件对应的任务，由于前面的任务没有正常执行所以后续的任务可能会产生多个错误
* 全部处理完成后弹出“处理完成……但是出现了错误”的提醒

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/ebfcbd60-d704-4c5b-bd0b-b4abf0d84980)

无论是否出现错误，输出的全部文本内容也会保存到主程序目录的 `output.log` 里。

（虽然写 shell 脚本的时候我还是比较喜欢在开头写上 `set -e` 的 |ω•`) ）

**Comment by Benson1997** [comment]
非常感谢大哥，有没有赞助二维码放出，送个coffee 😘

**Comment by TransparentLC** [comment]
> 如果是想要 放大图片后，自动运行 `cjxl {input} {output} -q 90 -e 9` 这个代码的话，这个代码应该加在哪里呢？

在“高级设定”里加上了，请参考 README.md 里的[命令示例](https://github.com/TransparentLC/realesrgan-gui#%E9%AB%98%E7%BA%A7%E8%AE%BE%E5%AE%9A%E4%B8%AD%E7%9A%84%E4%BD%BF%E7%94%A8%E6%9C%89%E6%8D%9F%E5%8E%8B%E7%BC%A9%E6%9C%89%E6%8D%9F%E5%8E%8B%E7%BC%A9%E8%B4%A8%E9%87%8F%E5%92%8C%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8E%8B%E7%BC%A9%E5%90%8E%E6%9C%9F%E5%A4%84%E7%90%86%E5%91%BD%E4%BB%A4%E6%98%AF%E4%BB%80%E4%B9%88)，可以试试有没有问题。

如果没有编码器 `cjxl` 的话，可以到 https://artifacts.lucaversari.it/libjxl/libjxl/latest/ 这里下载（第三方编译的二进制文件），解压后把 `cjxl` 放在 PATH 或主程序目录。

> 非常感谢大哥，有没有赞助二维码放出，送个coffee 😘

在“关于”那里就有，竟然没有注意到…… >_<

https://i.akarin.dev/donate/

如果好用的话，欢迎宣传到其他地方～

**Comment by Benson1997** [comment]
好的哦，感谢，coffee sent🤞

**Comment by TransparentLC** [comment]
把 `{output}` 改成 `{output:jxl}`，这么做可以在自定义的命令里保证输出的文件扩展名是 jxl，不过界面上输出的那个路径保留 png 扩展名不需要改。

> 自定义后处理命令，其实就是用命令行处理的作用对吧，那比如像ImageMagick的命令，也都可以用咯，是这样吗？

我也想到这点了，确实可以，在 README 里有个使用 ImageMagick 的例子。

**Comment by Benson1997** [comment]
自定义命令 jxl 测试成功。✨

自定义处理命令，太好用了，可以整合其他的命令行工具一气呵成。👍👍👍

**Comment by Benson1997** [comment]
老大，能否在【自定义压缩/后期处理命令】的输入框，增加一个历史记录的功能。方便点开之前用过的命令。不然命令记不住，或者输入不太方便😂

**Comment by TransparentLC** [comment]
没有这个打算，一方面是因为保存和轮换历史记录实现起来稍微有点麻烦，另一方面是我其实不太喜欢历史记录功能……（用大多数软件的时候都会尝试设置不保存历史记录）
