### ISSUE TITLE
请问想在use executable：xxx之后，输入cmd之前，先运行一次cd到app_path，需要怎么改代码

### ISSUE THREAD

**Issue by blacklein** [TransparentLC/realesrgan-gui#4]
请问想在use executable：xxx之后后，输入放大图像的cmd之前，让realesrgan-ncnn-vulkan先运行一次cd define.app_path的命令，需要怎么改代码才行？我想fork后重新编译打包mac应用，但改了好几次都不行，水平太低，求大佬指导，谢谢！

**Comment by blacklein** [comment]
task.py改成下面这样，其中wk_path是在define.py中定义为os.chdir(app_path)，这样写改对吗？
realesrgan前面的./需要去掉吗？
```
            cmd = (
                define.WK_PATH,
                './realesrgan-ncnn-vulkan',
                '-v',
                '-i', inputPath,
                '-o', outputPath,
                '-s', str(self.config.modelFactor),
                '-t', str(self.config.tileSize),
                '-n', self.config.model,
                '-g', str(self.config.gpuID),
```

**Comment by TransparentLC** [comment]
`os.chdir` 不是这么用的。以及 subprocess.Popen 不等于在 Shell 里执行命令（除非加了 `shell=True`，参见 [Python 官方文档](https://docs.python.org/zh-cn/3/library/subprocess.html#subprocess.Popen)），所以这个 `./` 也是不需要写的。按照你说的应该这么写：

```python
cmd = (
    ...
)
os.chdir(define.APP_PATH)
with subprocess.Popen(cmd, ...):
    ...
```

**Comment by blacklein** [comment]
<img width="658" alt="截屏2022-07-07 22 09 09" src="https://user-images.githubusercontent.com/69177971/177794121-2e03bb1d-6a9e-4932-817c-5d5782d73dd8.png">
之所以又想折腾了，是因为试了下，如果工作路径就在model所在的目录，那么哪怕命令里面是全路径，以及input、output路径都不在工作路径的，model还是能够运行的，所以猜测关键问题就在工作路径上，只要工作路径改到app_path，理论上应该就能解决之前issue里提到的所有问题了，我先试一下，改成下面这样，稍后再来更新反馈情况
```
            cmd = (
                define.RE_PATH,
                '-v',
                '-i', inputPath,
                '-o', outputPath,
                '-s', str(self.config.modelFactor),
                '-t', str(self.config.tileSize),
                '-n', self.config.model,
                '-g', str(self.config.gpuID),
                ('-x' if self.config.useTTA else ''),
            )
            os.chdir(define.APP_PATH)
            with subprocess.Popen(
                cmd,
                stderr=subprocess.PIPE,
                universal_newlines=True,
```

**Comment by blacklein** [comment]
成功了！心情如拨云见日！只是一行代码就解决了之前的所有困扰！
按照下面的目录树结构打包成macOS应用，一开始提示应用损坏，运行`xattr -cr path_to_app`后就能启动了，双击启动后放大图像成功！所有问题关键就是工作路径！非常感谢大佬的耐心指导，解决方法意外的简单！

```
Real-ESRGAN GUI.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   ├── config.ini
    │   ├── models
    │   │   ├── realesr-animevideov3-x2.bin
    │   │   ├── realesr-animevideov3-x2.param
    │   │   ├── realesr-animevideov3-x3.bin
    │   │   ├── realesr-animevideov3-x3.param
    │   │   ├── realesr-animevideov3-x4.bin
    │   │   ├── realesr-animevideov3-x4.param
    │   │   ├── realesrgan-x4plus-anime.bin
    │   │   ├── realesrgan-x4plus-anime.param
    │   │   ├── realesrgan-x4plus.bin
    │   │   └── realesrgan-x4plus.param
    │   ├── realesrgan-gui
    │   └── realesrgan-ncnn-vulkan
    └── Resources
        └── Appicon.icns

4 directories, 15 files
```

**Comment by blacklein** [comment]
第一个问题我也不清楚，我只知道这个命令能够解决大部分非appatore下载mac应用打不开的问题，很多开源项目编译好基本都有报错说文件损坏的这个问题，我自己猜测可能和软件签名有关。
第二个问题我明天上传这两个文件到这里，电脑已经关了
第三个问题我也认为不需要自解压，那样速度可能更慢，我测了时间，终端打开和打包app打开，速度是一样的，都要20秒左右，但app好处是可以直接安装在application文件夹里，双击就能用，主要是方便

**Comment by blacklein** [comment]
info.plist的内容

```
{
	CFBundleDisplayName = "Real-ESRGAN GUI";
	CFBundleIdentifier = test;
	CFBundleVersion = "0.2.5.0";
	CFBundlePackageType = APPL;
	CFBundleSignature = RLES;
	CFBundleExecutable = "realesrgan-gui";
	CFBundleName = "Real-ESRGAN GUI";
	CFBundleIconFile = "Appicon.icns";
	LSEnvironment = {
		LANG = "zh_CN.UTF-8";
	};
}
```
[info-plist+icon.zip](https://github.com/TransparentLC/realesrgan-gui/files/9068776/info-plist%2Bicon.zip)

**Comment by TransparentLC** [comment]
找了一些 Info.plist 的示例，但是似乎都是下面这种 XML 格式的？

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleGetInfoString</key>
  <string>Foo</string>
  <key>CFBundleExecutable</key>
  <string>foo</string>
  <key>CFBundleIdentifier</key>
  <string>com.your-company-name.www</string>
  <key>CFBundleName</key>
  <string>foo</string>
  <key>CFBundleIconFile</key>
  <string>foo.icns</string>
  <key>CFBundleShortVersionString</key>
  <string>0.01</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>IFMajorVersion</key>
  <integer>0</integer>
  <key>IFMinorVersion</key>
  <integer>1</integer>
</dict>
</plist>
```

**Comment by blacklein** [comment]
这个我不太懂，我用的info里面就这些内容，也能运行

**Comment by blacklein** [comment]
嗯appstore下载的app的info文件里面确实是大佬说的xml代码格式，但实测两种都可以，所以不确定，apple一直在努力简化和语义化代码，可能我下载到的示例是目前简化过的？

**Comment by TransparentLC** [comment]
试着改了一下打包脚本，现在 Actions 里面的 macOS 版已经变成 app bundle 了。不过  `Real-ESRGAN GUI.app/Contents/MacOS` 里并没有包含 real-esrgan-ncnn-vulkan 的相关文件，在 release 的时候会加上。这个版本并没有使用 `--onefile`。

测试一下是否可以正常使用？

**Comment by blacklein** [comment]
action下载artifact实测，可以运行，因为没用--onefile，启动速度秒开，而onefile需要20秒左右才能打开，建议release也不要用onefile，没问题，大佬可以加入模型发release了，建议简介也改一下，可以帮到很多mac用户

**Comment by blacklein** [comment]
<img width="372" alt="截屏2022-07-09 22 44 20" src="https://user-images.githubusercontent.com/69177971/178110748-13eb90b0-d5f0-4ec4-9921-3a1b7bdf4f8f.png">
但是报损坏的问题依然存在，需要运行xattr -cr命令（只需要做一次）清除扩展属性后才能启动，其他目前没碰到问题

**Comment by TransparentLC** [comment]
Release 已经发布了，`realesrgan-gui-macos-appbundle-v*.tar.xz` 解压后就是 app bundle。

**Comment by blacklein** [comment]
已从release下载实测，除了需要xattr -cr清除扩展属性才能启动外，没有其他问题，感谢大佬！

**Comment by TransparentLC** [comment]
也感谢你提供的和 macOS 相关的帮助～（我把这个写到了 README 最后的“致谢”部分）

**Comment by blacklein** [comment]
这个项目对我用处很大，使用体验很方便，还能帮到大佬，我不胜荣幸:)

PS：想请问下Downsample是模型自带的还是其他项目？

**Comment by TransparentLC** [comment]
除了图片放大之外的图像处理任务，比如这个 downsample、GIF 的拆解合成、放大后图片的有损压缩等等，都是使用 PIL 完成的。

**Comment by blacklein** [comment]
好的，感谢~
