### ISSUE TITLE
请求添加对tif格式的支持！

### ISSUE THREAD

**Issue by Benson1997** [TransparentLC/realesrgan-gui#42]
老大，请问能否添加一下对tif格式的支持，有些电子书是tif格式的压缩的pdf。😊

用命令行试了一下，realesrgan-ncnn-vulkan.exe是支持tif格式的。😃

非常感谢！😍

![image](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/985d1f6b-ae83-48ea-8f76-3385f22afcd8)

**Comment by TransparentLC** [comment]
既然那个支持的话那我也在 GUI 里把支持加上了，不过输出没办法使用 TIFF 了，所以输出的文件默认会使用 PNG 或 WebP 格式。

然后如果是处理这种书籍的图片的话，可以去试试隔壁的[“书之溯源 SourceBook”](https://github.com/tumuyan/SourceBook-Dataset)模型，这个模型需要搭配他修改过的程序使用，如果覆盖掉 GUI 目录的原版程序或许就可以在 GUI 中使用了？（不过我没测试过，目前暂时不会考虑适配改版程序）

**Comment by Benson1997** [comment]
好的，感谢透明！😘
