### ISSUE TITLE
最好用的一个  要是第一次通过拖放打开文件路径就好了 

### ISSUE THREAD

**Issue by haha0803** [TransparentLC/realesrgan-gui#45]
启动界面的时候通过拖放文件打开文件路径就好了  希望改进

**Comment by TransparentLC** [comment]
也就是说，把文件拖到主程序上，启动的时候就会直接把输入设定成那个文件的路径？

**Comment by haha0803** [comment]
是的 你把文件托到图标上软件启动起来之后 图片就自动输入路径了 就是你说的意思



在 2023-09-24 14:19:27，"✨小透明・宸✨" ***@***.***> 写道：

也就是说，把文件拖到主程序上，启动的时候就会直接把输入设定成那个文件的路径？

**Comment by haha0803** [comment]
是的      你把文件托到图标上软件启动起来之后  图片就自动输入路径了 就是你说的意思发自我的华为手机

**Comment by TransparentLC** [comment]
已添加，可以下载 Actions 的最新版本试试看。

**Comment by haha0803** [comment]
下载试过了 可以了  更新速度真快 点赞赞
