### ISSUE TITLE
添加终止按钮

### ISSUE THREAD

**Issue by BoxuanZng** [TransparentLC/realesrgan-gui#5]
在“开始“按钮旁边添加”终止“按钮，在点击”开始“按钮后有效，可以终止realesrgan的所有进程（不包括自己）

**Comment by BoxuanZng** [comment]
> 在“开始“旁边添加”终止“按钮，在点击”开始“按钮后有效，可以终止realesrgan的所有进程（不包括自己）

**Comment by TransparentLC** [comment]
似乎不太好弄啊 …_φ(･ω･` )

为了不让主界面卡住，开始放大时是另外开了一个线程处理这些任务的，但是我找了一下似乎在 Python 这边没有提供强行干掉线程的方法。如果通过全局变量之类的办法决定是终止还是继续执行下去的话，也没办法在执行单个 Real-ESRGAN 进程的中途把它干掉，至少得等到执行结束之后，但是这样也没有中途终止的意义了。因为这些原因所以我暂时不会考虑加入这个功能。
