### ISSUE TITLE
深色模式下，滚动条能否统一成深色呢？

### ISSUE THREAD

**Issue by Benson1997** [TransparentLC/realesrgan-gui#59]
感谢透明，软件太好用啦。有一个小小的问题，就是在深色模式下，滚动条还是浅色的，看看有没时间搞一下，那就完美了。 感谢！🤞

![image](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/e9c98f63-dc67-44c4-acde-14d08d52355d)

**Comment by TransparentLC** [comment]
这个带滚动条的文本框使用的是 tkinter.scrolledtext 的 ScrolledText，因为滚动条是 tk 的控件所以样式是直接跟随系统的，没有应用 ttk 的样式。

我从 `tkinter/scrolledtext.py` 复制了一份 ScrolledText 的相关代码，但是把滚动条改成了使用 ttk.Scrollbar，这样就解决了。

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/f7df5b92-0f36-4443-8772-8242fd69ab44)

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/078fb9b3-95d1-4caa-bc9a-fdcc3569ad03)

**Comment by Benson1997** [comment]
太棒了，感谢透明哥🤞
