### ISSUE TITLE
[REQUEST] ADD SUPPORT FOR SPAN, AND TILE SIZE 2048 AND NO TILE.

### ISSUE THREAD

**Issue by FlotingDream** [TransparentLC/realesrgan-gui#66]
[REQUEST] ADD SUPPORT FOR SPAN, ADD TILE SIZE 2048, ADD NO-TILING.

https://github.com/TNTwise/SPAN-ncnn-vulkan

I simply test this by replacing the file 'realesrgan-ncnn-vulkan.exe' in TransparentLC/realesrgan-gui by 'span-ncnn-vulkan.exe' in 'https://github.com/TNTwise/SPAN-ncnn-vulkan', then rename, choose the SPAN model, the realesrgan-gui worked fine. So it's very simple.

And SPAN is fast and no vram hungry, so bigger tile size and no-tile is needed.

thx!

**Comment by TransparentLC** [comment]
I have no plans to support other upscalers. If you replace other `***-ncnn-vulkan` and it works, then it works and you can use it at your own risk.

Adding a tile size of 2048 is easy. But what is no-tiling? Does it mean `-t 0`? This means setting the tile size automatically.

**Comment by FlotingDream** [comment]
> I have no plans to support other upscalers. If you replace other `***-ncnn-vulkan` and it works, then it works and you can use it at your own risk.
> 
> Adding a tile size of 2048 is easy. But what is no-tiling? Does it mean `-t 0`? This means setting the tile size automatically.

SPAN is worth to add, and maybe an experimental option for span-ncnn-vulkan choose would be really nice.

no-tiling means tile-width=width tile-height=height and prepadding=0

I checked 'https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/blob/37026f49824c5cf84062e7c6a5dd71445dcf610f/src/realesrgan.cpp'
 seems set - t inf (tile size bigger than width and height) can work too. (and prepadding=0, seems no flag for prepadding)

so no-tiling means like '-t 10240' 

just really big tile size

thx.

**Comment by TransparentLC** [comment]
Added 2048 and 4096 to the tile size combobox.

Also, it is now possible to set the paths of the upscaler (e.g. the span-ncnn-vulkan's executable, if its CLI is compatible with Real-ESRGAN-ncnn-vulkan) by manually editing `upscaler` and `modeldir` in `config.ini`.

**Comment by FlotingDream** [comment]
;)
thx!
