### ISSUE TITLE
请求添加几个新的模型文件（修复模糊的图）

### ISSUE THREAD

**Issue by Benson1997** [TransparentLC/realesrgan-gui#67]
在下小白研究了一下午，不会用ncnn，好像是没安装好环境，过于复杂了。不知道是不是可以请求添加几个新款使用的模型，不胜感激！🤞🤞

现有的几个模型，对于比较模糊的原图不太能修复细节，所以希望可以尝试以下几个新的模型。看官网上的图片效果还不错呢。

ps: 如果太大了，能否发网盘或者邮箱 lee987@qq.com ，都可以的😂，感谢感谢！！😊😊

https://openmodeldb.info/models/4x-LSDIRplus
![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/9844a8c6-c6a5-44b7-ae70-0ee6be30fecc)

https://openmodeldb.info/models/4x-SPANkendata
![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/9479848d-f45e-4d97-9eae-d724bb565d4e)

https://openmodeldb.info/models/4x-Nomos8kSCHAT-L
![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/1df8cfda-d176-42f8-8260-5c0be809e827)

**Comment by TransparentLC** [comment]
只有 4xLSDIRplus 可以转换并正常使用，这个我已经上传了。另外两个不是 ESRGAN 的模型（注意下载按钮下面的 Architecture）。

**Comment by Benson1997** [comment]
好的，明白了，非常感谢👍👍

**Comment by Benson1997** [comment]
实测以下，好像没有网站上效果那么夸张， 哈哈，正常的吧。

![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/a8f8a82d-577c-47bb-bd99-4d0d6ce8a082)

**Comment by TransparentLC** [comment]
这截图怎么看上去像是 NearestNeighbor 放大的样子……

实际的放大效果还是很不错的，和演示图基本一致，不过开 TTA 反而会减少细节。我用这个模型试了一下：

原图：https://raw.githubusercontent.com/Phhofm/models/main/4xLSDIRplus/examples/input/Input_13.png
![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/1eded2fd-9c31-43c5-aeae-c2999675827f)

原图：https://raw.githubusercontent.com/Phhofm/models/main/4xLSDIRplus/examples/input/Input_5.png
![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/27c338f4-0ef7-4b7f-9371-8fa3fc07aa37)

原图：https://raw.githubusercontent.com/Phhofm/models/main/4xNomos8kSC_results/input/seeufer.png
![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/da638eba-bb96-485d-bbd2-1d04b6e4ba68)

原图：https://raw.githubusercontent.com/Phhofm/models/main/4xNomos8kSC_results/input/palme.png
![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/a5e6eb21-4f1c-43db-be5e-666b794b6834)

**Comment by Benson1997** [comment]
好奇怪，是我参数没设置对吗，呜呜😢😢，同样的模型，怎么我出不来您这个效果。

![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/7827d61f-e38d-4b7e-9c52-2869ecbebceb)

![图片](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/9870f84b-bd6d-4bea-b057-c07066b64478)

![Snipaste_2024-02-28_00-01-06 (4xLSDIRplus x2)](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/d930b791-c03d-4dc7-9c10-1a2854148226)

**Comment by TransparentLC** [comment]
你应该是没有使用原始图片而是直接把模型页面上那个 NearestNeighbor 放大过的演示图截图了，这样的图片作为输入的话用什么模型都不会有理想的效果的。

另外，不建议使用 NearestNeighbor 进行降采样（除非你知道你在做什么）。

**Comment by Benson1997** [comment]
恩恩，用input那个原图可以了😊。好像用 realesrgan-x4plus 也能出来差不多的效果，哈哈。pdf导出来的图文的图片，是不是只要 realesrgan-x4plus 就够用了呢，日常主要用来处理图文的超分。

像下图这类的图片，好像怎么弄图片都没办法，效果很有限（是不是因为这个图不是扫描的原图呢）。
![0070](https://github.com/TransparentLC/realesrgan-gui/assets/111626633/d3a7fefa-4d4d-41b3-8ac2-f47ab22644d1)

**Comment by TransparentLC** [comment]
因为这张图的 JPEG artifacts（也就是压缩后出现的小格子痕迹）太严重了，覆盖了原图的绝大部分细节。

先用 PS 的“减少杂色”处理那些 artifacts，因为处理后的图有点模糊所以缩小 50%：

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/8952f1f4-2338-40c8-952d-baeccf38d95b)

然后尝试用 realesrgan-x4plus 放大，看上去一般但这已经是效果最好的了……

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/b1611ebc-9455-466a-b79a-6a3751ab232d)

**Comment by Benson1997** [comment]
非常感谢透明哥 🤞🎁
