### ISSUE TITLE
建议更新一下readme, macOS本地编译出错

### ISSUE THREAD

**Issue by miku1958** [TransparentLC/realesrgan-gui#69]
跟着readme编译, 但遇到以下问题

- 安装python
`brew install python@3.12`外, 还需要`brew install python-tk`

- 没有pip install -r requirements.txt

**Comment by TransparentLC** [comment]
也许你可以直接在 README 里补充然后提交 PR？

`pip install -r requirements.txt` 的话，我记得`macos-build-script.sh` 里面是有这一行的来着...

**Comment by miku1958** [comment]
看漏了, 确实在macos-build-script.sh里

**Comment by miku1958** [comment]
开了 https://github.com/TransparentLC/realesrgan-gui/pull/70
