### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by kirill0ermakov** [TransparentLC/realesrgan-gui#7]
Hello! Maybe in future you make English version? I can and want help with this!

**Comment by TransparentLC** [comment]
![](https://user-images.githubusercontent.com/47057319/189609143-743cc2f3-ac15-4338-accf-e72b5bbec57e.png)

The application's English translation is already included and used by default if there is no translation for the language currently in use. But any help on improving existing translations for the application or README.md would be greatly appreciated!

**Comment by kirill0ermakov** [comment]
That's cool! I want to help for translate for UA language, but unfortunately did not understand how to do it. There is everything in Japanese README :)

**Comment by TransparentLC** [comment]
First of all you need to check your locale by running `python -c "import locale;print(locale.getdefaultlocale()[0])"` in the terminal. For Ukrainian I guess the locale should be `uk_UA`.

If you want to add translations for the application, you need to edit the [`i18n.ini`](https://github.com/TransparentLC/realesrgan-gui/blob/master/i18n.ini). Append a new section named after comma-separated locales and fill the key-value pairs with your translations. Use the English translations as an example:

```ini
[en_US, en_GB]
Input = Input (file or folder)
Output = Output
ResizeMode = Resize mode
ResizeModeRatio = Ratio
ResizeModeWidth = Scale to width
ResizeModeHeight = Scale to height
...
```

For README translations, it is recommended to save it in a file named `README.[locale].md`. Example: `README.uk-UA.md`, `README.en-US.md`

By the way, the README.md is written in Simplified Chinese, not Japanese😂

**Comment by kirill0ermakov** [comment]
[uk_UA]
Input = Вхід (файл або папка)
Output = Вихід
ResizeMode = Режим зміни розміру
ResizeModeRatio = Співвідношення
ResizeModeWidth = Масштаб по ширині
ResizeModeHeight = Масштаб по висоті

Sorry, I sometimes confuse Chinese and Japanese, although Chinese is more geometrically correct :) What should I do next to finish the translation?

**Comment by TransparentLC** [comment]
1. Fork this repositiory to create a personal copy in your account, then clone the forked repositiory on your local machine. 
2. Finish the remaining translations then append them to the end of `i18n.ini`.
3. Copy `README.md` to `README.uk-UA.md` then translate it. (If you want to do that)
4. Commit your changes and push them to your repository.
5. Open a pull request in my repository and I will merge it if everything is OK.

You can also see this more detailed contribution tutorial: [firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions/blob/main/translations/README.ua.md)

**Comment by TransparentLC** [comment]
I have translated the README.md into [English](https://github.com/TransparentLC/realesrgan-gui/blob/master/README.en-US.md).

**Comment by kirill0ermakov** [comment]
I done!

**Comment by kirill0ermakov** [comment]
Oh, sorry! This is my first experience work this GitHub fork. Please check, I hope everything is correct now.

**Comment by TransparentLC** [comment]
I have merged your PR and created a new release with your translation. Thanks for your contributing!

![](https://user-images.githubusercontent.com/47057319/192502239-59481c54-0173-4147-999b-2f55e5cb947d.png)
