### ISSUE TITLE
使用最新actions build+upscayl-bin-20240421-145149超分出现报错

### ISSUE THREAD

**Issue by laplus114** [TransparentLC/realesrgan-gui#75]
使用原版的realesrgan-ncnn-vulkan不会出现此问题。`Traceback (most recent call last):
  File "task.py", line 325, in taskRunner
  File "task.py", line 99, in run
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8f in position 6: illegal multibyte sequence`

**Comment by TransparentLC** [comment]
是所有图片还是特定的几张图片会出现这个问题？如果是后者的话，是否可以提供原始图片？

**Comment by laplus114** [comment]
> 是所有图片还是特定的几张图片会出现这个问题？如果是后者的话，是否可以提供原始图片？

应该是所有图片，我尝试了几张图片都会出现相同的问题，进度条走到99%然后跳出这个错误

**Comment by TransparentLC** [comment]
https://github.com/upscayl/upscayl-ncnn/commit/980715d68b771c7e7dd8b59c0743f5088b78021e

从这个 commit 开始 upscayl 的输出里添加了 Emoji，所以出现了这种编码问题。比如我在终端里直接运行的话：

![](https://github.com/TransparentLC/realesrgan-gui/assets/47057319/c5de8d78-6e14-4e9b-9065-99719bbe1563)

在我修复之前先使用这个 commit 之前的版本吧（最后一个应该是 upscayl-bin-20240209-044609）。
