### ISSUE TITLE
没有脸部增强的选项

### ISSUE THREAD

**Issue by hanweinjq** [TransparentLC/realesrgan-gui#78]
没有脸部增强的选项

**Comment by TransparentLC** [comment]
Real-ESRGAN 有这个功能吗？

**Comment by TransparentLC** [comment]
你说的脸部增强应该是 Real-ESRGAN 的作者的另一个项目 [GFPGAN](https://github.com/TencentARC/GFPGAN) 的功能，不过和这个项目就没有关系了。
