### ISSUE TITLE
[FEATURE_REQUEST] option for multiple upscale procedure

### ISSUE THREAD

**Issue by the-liquid-metal** [TransparentLC/realesrgan-gui#80]
It is a madness situation for users who have to do upscale multiple times if their hardware has limited spec. If a single upscale on a single image needs 3 minutes to finish, how much time to finish consecutive upscale? n^2?. Even worse, Real-ESRGAN does not provide "realesrgan-x2plus" and "realesrgan-x3plus" models.

I've experienced this, when upscaling 900px or less to 4K. The lessons I learned: i have to upscale it without AI first, and then with AI.

I propose that realesrgan-gui provides additional option as select widget with items:
- always upscale with AI.
- upscale without AI first, followed by with AI.

This new option is only relevant with: "scale to width" or "scale to height" options, and only applied if those scales is greater than pixels produced by first upscale. 

There should be a visible note for this new option.

**Comment by the-liquid-metal** [comment]
A fundamental question: does realesrgan-gui perform multiple upscales if the "scale to width" or "scale to height" options have values greater than the pixels produced by the first upscale, or simply run single upscale and ignoring the value?

**Comment by TransparentLC** [comment]
I don't know what "upscale it without AI" means.

Multiple upscales is performed if upscale once doesn't reach the specified resolution. If you upscale a 900px image to 4k with a 4x model, the GUI will run Real-ESRGAN for twice: upscale 900px to 3600px, then to 14400px, then downsample to 4k. This is what [waifu2x-caffe](https://github.com/lltcggie/waifu2x-caffe) does, as you can notice it from upscaling time: ... = 1.99x = 2.00x < 2.01x = ... =3.99x = 4.00x < 4.01x = ...

You may think that upscaling from 3600px to 14400px with Real-ESRGAN is a waste in this case, but I think it is more like a compromise. Upscaling from 3600px to 4k with lanczos or bicubic or something else without running Real-ESRGAN makes no sense.

**Comment by the-liquid-metal** [comment]
> I don't know what "upscale it without AI" means.
> 
It means simple resizing with classical algorithms to the nearest larger dimension.

Suppose that i want my picture to have 4096px. My current picture is 900px. So, the nearest larger dimension is 1024px (4096÷4). Before i do upscale with 4x model, i do resize my image from 900px to 1024px.

This will save a lot of time.

**Comment by the-liquid-metal** [comment]
FYI, XnConvert (or any similar app) only takes a few seconds to resize (lanczos) with dozens of images.

**Comment by TransparentLC** [comment]
I accept and plan to implement this feature.

Document how it should be implemented here. Imagining if you are upscaling from 1000px to 16001px (not divisible by multiples of 4) with a 4x model:

1. `math.log(16001 / 1000, 4) = 2.00005`, so Real-ESRGAN need to be run twice (`4 ** 2 = 16`x upscale). I set a threshold here, the pre-upscale is only enabled if the fractional part is lower than 0.5.
2. Calculate the pre-upscale size: `math.ceil(16001 / (4 ** 2)) * (4 ** 2) = 1001`
3. The image will be upscaled to 1001px via lanczos, then be upscaled via Real-ESRGAN twice to 4004px and 16016px, then downsample to 16001px.

**Comment by the-liquid-metal** [comment]
O my goodness, this turns out to be a bit more complicated than I imagined.

**Comment by TransparentLC** [comment]
You can try this feature from the latest build from actions now.

**Comment by TransparentLC** [comment]
real-esrgan-ncnn-vulkan uses libwebp and [Windows Imaging Component (only on Windows) / stb_image](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/blob/37026f49824c5cf84062e7c6a5dd71445dcf610f/src/main.cpp#L386) to save images. The webp comes from real-esrgan-ncnn-vulkan is lossless. For jpg it uses the best quality the encoder supports (1.0 for WIC and 100 for stb_image).

The lossy compression in the GUI only works on the final output if you enabled the option and the output extension is jpg or webp. In this case the GUI will let real-esrgan-ncnn-vulkan outputs a lossless webp, then [compress by itself](https://github.com/TransparentLC/realesrgan-gui/blob/5f8708d3d56be53a0e7cdf002f893f8e2051c3bb/task.py#L280). I enabled maximum compression options (method 6 for webp, optimize and progressive for jpg) in this procedure. If the GUI's lossy compression is not enabled then the output of real-esrgan-ncnn-vulkan will be used directly.

Pre-upscale [outputs a lossless png/webp](https://github.com/TransparentLC/realesrgan-gui/blob/master/task.py#L80). The compression level of this intermediate file should have no effect on the compression level of the final output.

**Comment by the-liquid-metal** [comment]
I have informed this app to my colleagues. Based on our discussion, We have some notes related to multiple upscale. My colleague found an alternative route and he showed me that this route was worth doing. The final output is slightly better than the first route (upsize → upscale), but not better than the original route (upscale → upscale → downsize).

Rather than immediately resizing to ¼X of the required final dimensions, we do upscale first and then resizing to ¼X of the required final dimensions. And the last step is still upscale 4x. so this route is: upscale → downsize → upscale.

This seems odd, but it is the best tradeoff between speed and quality. My previous test takes time roughly 15 minutes for original route, and 1,5 minutes for first route. The upsize step only takes time a fraction of second. So, if we do second route, it will be less than 2x required time for first route, which is less than 3 minutes. **It is still save a lot of time**.

Why is it less than 2x required time? Because dimension of 1st upscale (U1) is lesser then 2nd upscale (U2). The first route is actually doing U2, not U1.

We do first route if the dimensional differences is less than 10%, the second route for others. It is reasonable to keep these two routes exist, to optimize time. In our humble opinion, doing second route for every dimensional differences is not necessary, since we will not get significant quality improvement.

At the moment, realesrgan-gui already has "Try to pre-upscale with general algorithm" option. It does not need to be changed. The existence of the first and second routers does not need to be exposed to user, and there is no interaction between user and these two routers. **The app is automatically select which router will be used**. This requires a little additional calculation (hopefully 😄). After this procedure revision, "Try to pre-upscale with general algorithm" is slightly misleading, since upscaling is also involved in pre-upscale step. IMO, it should be changed to **"Try to pre-upscale first"**.

**Comment by the-liquid-metal** [comment]
Thank you for your effort to prove that method A/first route is always better than method B/second route.
- Fortunately we don't need accurate comparison represented by numbers. We only need shallow comparison with vision.
- Many of our images are imperfect with significant blur and/or noise. Instead of producing near identical image, we need tool that can produce improved image. That's why comparison numbers become irrelevant.

**Comment by TransparentLC** [comment]
It's hard to convince other people (at least me) with subjective comments like “... looks better”, that's the reason why we need objective image quality metrics like PSNR, SSIM, Butteraugli and so on.

The meaning of the experiment's result is that if there exists a corresponding perfect image, using method A on your imperfect image will be closer to it than method B.
