### ISSUE TITLE
[FEATURE_REQUEST] export formatted log

### ISSUE THREAD

**Issue by the-liquid-metal** [TransparentLC/realesrgan-gui#82]
At the moment, it is hard to benchmark anything using realesrgan-gui. Benchmarking is not limited to testing new features, but also to measuring model performance and output. Materialized benchmark is very important as a material for communication between people, especially with colleagues. For some people, at the end they have to make decision to be applied to their photosets collection based on these benchmarks.

The log text has insufficient data and is impractical to analyze. It would be great if any data related to the process can be exported. The log text can be left as is.

The formated log which I expected in the form of CSV, and has columns: filename, original size, size after preupscale, size of final output, original dimension, dimension after preupscale, dimension of final output, consumed time for preupscale, consumed time for upscale.

On the top of this table, all parameters which are applied in the "basic" and "advanced" tabs are outputed. Additional info if available: processor, memory, etc are also outputed. Between parameters+additional info and the table, there is a blank line separating them.

This formatted log is automatically created and placed in output folder with name "realesrgan-gui log [TIMESTAMP].txt"

**Comment by TransparentLC** [comment]
For benchmarking I suggest write your own script that calls the CLI. The usage scenario is niche and such a feature is not what this GUI is designed for.

**Comment by the-liquid-metal** [comment]
> For benchmarking I suggest write your own script that calls the CLI. The usage scenario is niche and such a feature is not what this GUI is designed for.

Sad to read that.

In the other issue, i had explained to you why we want to move from CLI to GUI: **it is impractical**. Before CLI we even used GUI. Why we moved from GUI: It consumes more resources which may slow down the main process. Whether it's true or not, we don't know for sure. We're just anticipating. With our limited spec, we have to calculate carefully.

Why we don't write our own app? Because we don't want to maintain it, just like most people. Maybe someone has already created an app that fits (or close) to our needs. We think your application has potential for that.

If you suggest sticking to the CLI for benchmarking, while using the GUI for output, that means you're suggesting we work twice as hard (and outputting twice, and spend time twice too).

IMHO, this app is already half way to realizing materialized benchmark: there is already "config.ini" and "output.log" written by this app. The content of formatted log which I requested contains the same as the "config.ini", plus things from captured time and file size.

All other features of this app is fine. I thank you for the additional features that I requested and have been created. This will reduce our working time significantly. The only missing piece is improvements to the way we communicate with colleagues. materialized benchmark is that piece.

I know this is a little deviated from what you planned, but please consider our request.
Thank you.

**Comment by TransparentLC** [comment]
If you want to compare different models with a lot of images, it is easier to write a loop in your own script, sit down and have some coffee, waiting for the script to complete, than switch between models in the GUI and press "start" by yourself once in a while. If you need quality metrics like SSIM, just use ImageMagick or something else. You can decide to output the results in plain text or csv or json or whatever format you want, but it would be too complicated to put this as an option in the GUI.

If you choose scripts and CLI for benchmarking, you can combine many existing tools or libraries which meet your needs.

This GUI is designed for people who want to make thir low-res images looks better, **not for benchmarking**.
