### ISSUE TITLE
REALCUGAN无法使用

### ISSUE THREAD

**Issue by AxionnG** [TransparentLC/realesrgan-gui#83]
版本：Automated build 20240131-130138
           [realesrgan-gui-windows-bundled-v0.2.5.0.7z]

问题：在readme文档中《我觉得 Real-CUGAN 的放大效果比 Real-ESRGAN 更好》章节
           操作步骤2：“在 config.ini 中将 upscaler 设定为 realcugan-ncnn-vulkan[.exe] 的路径“
           config.ini中无“upscaler”键值，手动添加后开启realesrgan-gui.exe，未生效，关闭realesrgan-gui.exe后，config.ini内该手动添加键值消失。

**Comment by TransparentLC** [comment]
添加 Real-CUGAN 支持后我暂时还没有发布新的 release，你可以从 actions 下载最新的主程序然后覆盖。

**Comment by evafans** [comment]
> 添加 Real-CUGAN 支持后我暂时还没有发布新的 release，你可以从 actions 下载最新的主程序然后覆盖。

你好，有没有对应的config.ini，旧的config里面无法设置upscaler。

**Comment by AxionnG** [comment]
收到，感谢！

**Comment by hbgodseeker** [comment]
找到了这个已经关闭的issue解决了CUGAN问题，感谢大大的持续开发
