### ISSUE TITLE
如果可以支援影片處理就好了

### ISSUE THREAD

**Issue by Rosabis** [TransparentLC/realesrgan-gui#86]
因為有時候可能需要做影片放大

**Comment by TransparentLC** [comment]
这个项目是处理图片的，虽然把每一帧保存成图片然后处理再拼回视频也行……

如果处理视频的话可以出门右转：

https://github.com/HolyWu/vs-realesrgan
https://github.com/Kiyamou/VapourSynth-RealCUGAN-ncnn-Vulkan
