### ISSUE TITLE
请问使用cugan模式、models-se#up4x-conservaive模型、4倍固定倍率的情况下，实际运行的命令行完整是怎么样的？

### ISSUE THREAD

**Issue by hyrulelinks** [TransparentLC/realesrgan-gui#88]
<img width="502" alt="截屏2024-10-11 12 58 52" src="https://github.com/user-attachments/assets/d18e2714-0871-45c9-b5cc-287ef5f9dc23">

因为我直接运行命令行和用gui运行相同参数，得到的图像效果肉眼可见不同，所以想问下gui用的命令行是怎么样的，看看是不是我的命令行参数设置不对，谢谢！
@TransparentLC

**Comment by TransparentLC** [comment]
`realcugan-ncnn-vulkan -v -i input.png -o output.png -s 4 -t 0 -m /path/to/models/models-se -n -1 -g auto -c 1`

https://github.com/TransparentLC/realesrgan-gui/blob/d662c7fad3c7596033cac2e852813a541068e2e8/task.py#L110-L129

**Comment by hyrulelinks** [comment]
```
                denoiseLevel = {
                    'conservative': -1,
                    'no-denoise': 0,
```
官方仓库里面写的是-1是no effect，是不是应该反过来no-denoise是-1，conservative是0？

**Comment by hyrulelinks** [comment]
感谢耐心解答，那应该以源码为准，readme大概是写错了
