### ISSUE TITLE
请问集成GPU的CPU，有可能使用的上 realesrgan-gui 吗

### ISSUE THREAD

**Issue by Benson1997** [TransparentLC/realesrgan-gui#90]
透明哥好，请问以下两种情况的设备，好不好使用 realesrgan-gui ？

1. 现在一些轻型笔记本或者mini主机，并没有配备GPU，是不是就没办法使用realesrgan-gui 了，有别的办法吗？
（偶尔处理几张小朋友的卷子，老师拍照发的图太糊了。）

2. 一些新款的cpu，集成了GPU，这种情况可以使用吗？😊

**Comment by TransparentLC** [comment]
有 GPU 就可以用，但是如果是核显或者软件模拟的显卡（比如 Linux 虚拟机用的 llvmpipe）放大一张图片的耗时可能会是独显的好几倍，非常慢。

**Comment by Benson1997** [comment]
好的，感谢回复😀
