### ISSUE TITLE
关于文件选择和保存

### ISSUE THREAD

**Issue by ZhangSir9901** [TransparentLC/realesrgan-gui#94]
1、支持打开保护子目录的文件夹下面的全部文件；
2、支持保存到另外的指定目录。

其它的一切都好。

还有就是哪位大佬给讲讲内置几个模型的特点和用途。谢谢。

**Comment by ZhangSir9901** [comment]
期待下次更新。感谢作者的优秀作品。

**Comment by TransparentLC** [comment]
输入本来就是递归遍历所有子目录的，输出路径可以自己改。

自带模型的介绍 README 里有写：https://github.com/TransparentLC/realesrgan-gui?tab=readme-ov-file#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E6%A8%A1%E5%9E%8B
